@startuml
title Saga + CQRS: Agendar Consulta (Coreografia Assíncrona)

actor "Paciente" as User
participant "API Gateway" as Gateway
participant "Scheduling Command API" as SchedCmd
database "Scheduling DB" as WDB
queue "Message Broker" as Broker
participant "Patient Service" as PatSvc
participant "Physician Service" as DocSvc
participant "Scheduling Query API" as SchedQuery
database "Consultations Read DB" as RDB

autonumber

== 1. Início do Agendamento (Comando) ==

User -> Gateway : POST /api/consultas\n{patientId, physicianId, time}
Gateway -> SchedCmd : POST /appointments

activate SchedCmd

    SchedCmd -> WDB : INSERT Appointment (status = PENDING)
    WDB --> SchedCmd : OK (Retorna ID gerado)

    SchedCmd -> Broker : publish **AppointmentCreatedEvent**\n{apptId, patientId, physicianId...}

    SchedCmd --> Gateway : 201 Created
deactivate SchedCmd

Gateway --> User : 201 Created\n"A processar agendamento..."

== 2. Saga: Validações Paralelas (Coreografia) ==

group Validação de Paciente
    activate PatSvc
    Broker -> PatSvc : consume **AppointmentCreatedEvent**
    PatSvc -> PatSvc : Validar existência/dívidas
    PatSvc -> Broker : publish **PatientValidatedEvent**\n{apptId, valid: true}
    deactivate PatSvc
end

group Validação de Médico
    activate DocSvc
    Broker -> DocSvc : consume **AppointmentCreatedEvent**
    DocSvc -> DocSvc : Validar disponibilidade
    DocSvc -> Broker : publish **PhysicianAvailabilityConfirmedEvent**\n{apptId, valid: true}
    deactivate DocSvc
end

== 3. Conclusão da Saga ==

activate SchedCmd
    Broker -> SchedCmd : consume **PatientValidatedEvent**
    Broker -> SchedCmd : consume **PhysicianAvailabilityConfirmedEvent**

    note right of SchedCmd
      O serviço aguarda a chegada
      de ambos os eventos de sucesso
      para confirmar a consulta.
    end note

    SchedCmd -> WDB : UPDATE Appointment SET status = CONFIRMED

    SchedCmd -> Broker : publish **AppointmentBookedEvent**\n{Full Appointment Data}
deactivate SchedCmd

== 4. Atualização de Leitura (CQRS) ==

activate SchedQuery
    Broker -> SchedQuery : consume **AppointmentBookedEvent**
    SchedQuery -> RDB : INSERT/UPDATE AppointmentView
    RDB --> SchedQuery : OK
deactivate SchedQuery

@enduml