@startuml
title CQRS (Query Side): Ver Detalhes do Paciente (Médico)

actor "Médico" as User
participant "API Gateway" as Gateway
participant "Patient Query API" as QueryAPI
database "Patient Read DB\n(H2)" as RDB

autonumber

note right of User
  **Pré-condição:**
  O Médico já está autenticado
  e possui um Token JWT.
end note

User -> Gateway : GET /patients/{patientId}\n(Authorization: Bearer <JWT>)

Gateway -> Gateway : Valida Assinatura JWT
Gateway -> Gateway : Extrai **physicianId** do Token

Gateway -> QueryAPI : GET /patients/{patientId}\n(Header X-Physician-ID: {physicianId})

activate QueryAPI

    QueryAPI -> RDB : findOne({ \n  _id: {patientId}, \n  relatedPhysicianIds: {physicianId} \n})

    RDB --> QueryAPI : Documento do Paciente

    QueryAPI --> Gateway : 200 OK + DTO Detalhes
deactivate QueryAPI

Gateway --> User : 200 OK + JSON

@enduml