@startuml
 Patient-> PatientController : GET /api/patient/appointments\n?physicianName={name}
activate PatientController

PatientController -> AppointmentService : searchByPhysician(username,\nphysicianName)
activate AppointmentService

AppointmentService -> SpringBootPatientRepository : findByBaseUserUsername(username)
activate SpringBootPatientRepository
SpringBootPatientRepository --> AppointmentService : Patient
deactivate SpringBootPatientRepository

AppointmentService -> SpringBootAppointmentRepository : findByPatientAndPhysicianName(\npatient, physicianName)
activate SpringBootAppointmentRepository
SpringBootAppointmentRepository --> AppointmentService : List<Appointment>
deactivate SpringBootAppointmentRepository

AppointmentService --> PatientController : List<Appointment>
deactivate AppointmentService

PatientController -> AppointmentViewMapper : toAppointmentViewList(List<Appointment>)
activate AppointmentViewMapper
AppointmentViewMapper --> PatientController : List<AppointmentView>
deactivate AppointmentViewMapper

PatientController --> Patient : HTTP 200 OK + [AppointmentView]
deactivate PatientController
@enduml